spring:
  profiles:
    active: cloud

  application:
    name: InventoryTrack

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}

keycloak:
  client-secret: ${CLIENT_SECRET}
  token-url: ${TOKEN_URL}
  redirect-uri: ${REDIRECT_URI}


#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:54322/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres

#spring.security.user.name=user
#spring.security.user.password=123

#server.port=8000
